server:
  port: 8443
  ssl:
    #    key-store: /etc/nginx/certs/keystore.p12
    key-store: /Users/minseok95/caualerting/cau-noti.com/keystore.p12
    key-store-password: ${ssl.password}
    keyStoreType: PKCS12
    keyAlias: alerting
    enabled: true
  servlet:
    cookie:
      same-site: None
      secure: true

spring:
  sql:
    init:
      mode: never

  datasource:
    #    url: jdbc:mysql://cau-alerting-mysql:3306/alerting
    url: jdbc:mysql://43.201.161.211:3306/alerting
    username: user
    password: ${mysql.password} #"Abcd1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 60000
          starttls:
            enable: true

  redis:
    host: localhost
    port: 6379
    password: ${redis.password}

recaptcha:
  key:
    site: ${recaptcha.key.site}
    secret: ${recaptcha.key.secret}

jwt:
  secret: ${jwt.secret}

logging:
  level:
    org.springframework.security: DEBUG
