server:
  port: 8443
  ssl:
    key-store: /Users/minseok95/caualerting/cau-noti.com/keystore.p12
    key-store-password: ${ssl.password}
    keyStoreType: PKCS12
    keyAlias: alerting
    enabled: true
  servlet:
    cookie:
      same-site: None
      secure: true

spring:
  sql:
    init:
      mode: always

  config:
    activate:
      on-profile: dev

  datasource:
    url: "jdbc:mysql://localhost/alerting"
    username: "root"
    password: ${mysql.password} #"Abcd1234!"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        use_sql_comments: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 60000
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      password: ${redis.password}

recaptcha:
  key:
    site: ${recaptcha.key.site}
    secret: ${recaptcha.key.secret}

jwt:
  secret: ${jwt.secret}

logging:
  level:
    org.springframework.security: DEBUG
